### ISSUE TITLE
Is applyInverse required to work when the same object is passed to both args?

### ISSUE THREAD

**Issue by bogovicj** [imglib/imglib2-realtransform#13]
@axtimwalde 
Is it a requirement that every [InvertibleRealTransform](https://github.com/imglib/imglib2-realtransform/blob/9a47ebd859cdf86a9271cc63fe7526c3e9c80e4e/src/main/java/net/imglib2/realtransform/InvertibleRealTransform.java) work correctly when called like this (for example):
```
double[] tmp = ...
invertibleTransform.applyInverse( tmp, tmp );
```
?

If so, let's add it to the doc (possibly also for `RealTransform`s)

If not, then [this line](https://github.com/imglib/imglib2-realtransform/blob/9a47ebd859cdf86a9271cc63fe7526c3e9c80e4e/src/main/java/net/imglib2/realtransform/InvertibleRealTransformSequence.java#L61) in `InvertibleRealTransformSequence` will cause problems for any implementation that does not meet this requirement.

**Comment by axtimwalde** [comment]
Yes, this is a requirement.  Please add to the doc.

**Comment by bogovicj** [comment]
See the PR.  I think the one sentence is sufficient:

Implementations must support an in-place applyInverse (i.e., passing the same object as both <em>source</em> and <em>target</em>).

What do you think?

**Comment by axtimwalde** [comment]
Perfect.  Thanks!
