### ISSUE TITLE
AffineTransform3D.scale should take three parameters for potential anisotropic scaling

### ISSUE THREAD

**Issue by haesleinhuepf** [imglib/imglib2-realtransform#23]
Dear all,

I just tried to combine a translation, rotation and (anisotropic) scaling in an AffineTransform3D. However, `AffineTransform3D.scale(double s)` takes only one parameter. With a `Scale3D` you cannot scale an image centered (scaling and translation combined). Am I missing something? How would you guys do such an operation?

Thanks!

Cheers,
Robert

**Comment by axtimwalde** [comment]
Just added this https://github.com/imglib/imglib2-realtransform/commit/8df6a73c19073862181b4a349bbdc3ad25162c8e.  Until released, do
```java
final AffineTransform3D scale = new AffineTransform3D();
scale.set(
  s0, 0, 0, 0,
  0, s1, 0, 0,
  0, 0, s2, 0);
at.preConcatenate(scale);
```

**Comment by haesleinhuepf** [comment]
Great! Thanks a lot!

**Comment by axtimwalde** [comment]
Oh--and the other part in pseudocode:
at.translate(-center)
at.scale()
at.translate(center)
