### ISSUE TITLE
Behavior of empty RealTransformSequence

### ISSUE THREAD

**Issue by bogovicj** [imglib/imglib2-realtransform#24]
@axtimwalde 

The apply method for empty `RealTransformSequence` currently does nothing to its target point.

I'd expect either:
1) There to exist some way of determining that a `RealTransformSequence` object is empty.  
2) That an empty `RealTransformSequence` acts as the identity.

I'll file a PR once we make a choice.

**Comment by axtimwalde** [comment]
I like identity

**Comment by bogovicj** [comment]
Great, I'll make a PR.
