### ISSUE TITLE
Anybody willing to make a new release ?

### ISSUE THREAD

**Issue by NicoKiaru** [imglib/imglib2-realtransform#46]
Please!

I'd be happy to finally get rid of this bug: https://github.com/imglib/imglib2-realtransform/commit/a6466a4287fad9ac90ceea2b204353d6489f649e in the new pom scijava

**Comment by tpietzsch** [comment]
@axtimwalde @bogovicj

**Comment by ctrueden** [comment]
On the assumption of [release-ready master branches](https://imagej.net/develop/releasing#phases-in-depth), I cut the 4.0.2 release.

**Comment by NicoKiaru** [comment]
It's done, thanks to all!

**Comment by bogovicj** [comment]
thanks @ctrueden
