### ISSUE TITLE
Treating a non-invertible transform as an "inverse" in RealViews

### ISSUE THREAD

**Issue by bogovicj** [imglib/imglib2-realtransform#7]
## Short story
I think there should be methods in RealViews that take arguments of the types:
`RealViews.transform( RealRandomAccessible, RealTransform ) `
`RealViews.transformReal( RealRandomAccessible, RealTransform ) `
where the input RealTransform will be assumed to go from target to source space.

The current methods only accept `InvertibleRealTransforms`

## Longer story
I intend to file a PR related to this soon, but here's the background:

I've implemented a `DeformationFieldTransform`, i.e. a wrapper around a RAI that can act as a transformation - e.g. an `X x Y x Z x 3` can act as a 3d transform, and a `X x Y x 2` RAI can act as a 2d transform.

However, a transformation of this type is not invertible in general, but there are cases in which  it is important to treat it as if it were an "inverse" (goes from target to source): most especially so that it can be passed to `RealViews.transform`

The api as it is makes this a little tricky, here are the options that I see:

1. Ideally, it would be great if, say, `RealViews.transform` could accept a `RealTransform` (rather than an `InvertibleTransform`). This means one kind of has to "know what you're doing," in the sense that the passed RealTransform will be treated as an inverse for the purpose of rendering, but `RealTransformRandomAccessible` is already implemented such that this is okay. 

2. Make a wrapper around a `DeformationFieldTransform` that is an `InvertibleTransform` where applyInverse calls apply and apply does nothing.  This may not so bad as long as the object is only used in the `RealTransformRandomAccessible` but its not _really_ an `InvertibleTransform`. 

So I much prefer option 1. Looking forward to feedback.

**Comment by axtimwalde** [comment]
You can use `RealTransformRealRandomAccessible` directly:

```java
RealRandomAccessible<T> source;
RealTransform transform;
RealRandomAccessible<T> target = new RealTransformRealRandomAccessible(source, transform);
```

**Comment by bogovicj** [comment]
True.
Is that preferable?  Does it make sense to have both anyway?

`RealViews.transform` is slightly (lame reason maybe), but I can see how having both methods could get confusing.

**Comment by axtimwalde** [comment]
Well, I would leave it for now.  The method in `RealViews` would not do any intelligent magic but simply implement the above line of code but at the same time be potentially confusing.   So I think for now it's better to stick with the plain class that does the right thing already.

**Comment by bogovicj** [comment]
Sounds good.
